name: tmdb

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  dio: ^5.7.0
  get: ^4.6.6
  pretty_dio_logger: ^1.4.0
  fluttertoast: ^8.2.8
  shared_preferences: ^2.3.3
  hive_flutter: ^1.1.0
  zoom_tap_animation: ^1.1.0
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.17
  percent_indicator: ^4.2.4
  transparent_image: ^2.0.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_rating: ^2.0.2
  flutter_dotenv: ^5.2.1
  flutter_rating_stars: ^1.1.0
  like_button: ^2.0.5
  motion: ^2.0.1
  bounce: ^1.0.2
  double_back_to_close_app: ^2.1.0
  animated_toggle_switch: ^0.8.4
  lottie: ^3.3.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/images/
    - assets/screenshots/
    - assets/gif/
    - assets/icons/
    - .env
